config/routes.rb
Dooit::Application.routes.draw do
  resources :cases

  resources :contacts

  resources :services

  resources :companies

  resources :clients

  root :to => "companies#index"

end

app/models/case.rb
class Case < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  # GET /cases
  # GET /cases.xml
  def index
    @cases = Case.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cases }
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.xml
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clients }
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.xml
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @companies }
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts/new
  # GET /contacts/new.xml
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @contact }
    end
  end

  # POST /contacts
  # POST /contacts.xml
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        ContactMail.contact_send(@contact).deliver
        format.html { redirect_to(root_path, :notice => 'Contact was successfully created.') }
        format.xml  { render :xml => @contact, :status => :created, :location => @contact }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.xml
  def index
    @services = Service.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @services }
    end
  end

  # GET /services/1
  # GET /services/1.xml
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @service }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/cases/index.html.erb
<div class="cases">
  <p class="imagem">
    <%= link_to image_tag("pmpl.png"), "images/pmpl_large.png", :rel => "image"  %>
  </p>
  <p class="texto">
    <ul>
      <li>- Controle</li>
      <li>- Controle</li>
      <li>- Controle</li>
      <li>- Controle</li>
  </p>
</div>

app/views/clients/index.html.erb
<div class="clientes">
  <h1>Clientes</h1>
  
  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

  <%= image_tag("rails.png") %>

</div>

app/views/companies/index.html.erb
<div class="empresa">
  <table cellspacing="0" cellpadding="0">
    <tr>
      <td class="linha1 title">Agencia</td>
    </tr>
    <tr>
      <td class="linha2">
        A Dooit é uma empresa de soluções de tecnologia que busca melhorar o desempenho e a lucratividade, detectando as necessidades de cada empresa e apresentando soluções, para construir junto ao cliente uma idéia de sucesso. <br><br>
        A Dooit trabalha com o comprometimento ao cliente, utilizando uma metodologia para que possa ser entregue projetos, visando o tempo, custo e qualidade.
      </td>
    </tr>
  </table>
  
  <table cellspacing="0" cellpadding="0">
    <tr>
      <td class="linha1 title">Serviços</td>
    </tr>
    <tr>
      <td class="linha2">
        <ul>
          <li>
            Desenvolvimento de Web sites.
          </li>
          <li>
            Consultoria e desenvolvimento de software coorporativo.
          </li>
          <li>
            Criação de aplicativos móbile.
          </li>
        </ul>
      </td>
    </tr>
  </table>
</div>

app/views/contact_mail/contact_send.html.erb
<p>Novo contato</p>

<p>
  Dados<br>
  <strong>Nome:</strong> <%=@contact.name %><br>
  <strong>Email:</strong> <%=@contact.email %><br>
  <strong>Telefone:</strong> <%=@contact.telephone %><br>
  <strong>Assunto:</strong> <%=@contact.subject %><br>
  <strong>Descrição:</strong> <%=@contact.description %>
</p>

app/views/contacts/_form.html.erb
<div class="contato">
  <table class="telefonico" cellspacing="0" cellpadding="0">
    <tr>
      <td class="linha1 title">Contato via Telefone</td>
    </tr>
    <tr>
      <td class="linha2">
        <p class="telefone">
        <span>Telefone:</span> 
        (11) 5979-6112 <br>
        (11) 6698-3021 <br>
        (11) 7642-1605 <br> <br>
        </p>
        <p>
        <span>Email:</span> 
        wollase.andrade@gmail.com <br>
        guilherme.barbosa90@gmail.com <br> <br>
        </p>
        <p>
        <span>Atendimento:</span>
        Segunda a Sexta das 9:00 as 18:00
        </p>
      </td>
    </tr>
  </table>
  
  <p class="ou">
  Ou
  </p>
  
  <table cellspacing="0" cellpadding="0">
    <tr>
      <td class="linha1 title">Contato via Email</td>
    </tr>
    <tr>
      <td class="linha2">
        <%= form_for(@contact) do |f| %>
          <p>
            <%= f.label :name, "Nome" %>
            <%= f.text_field :name %>
          </p>
          <p>
            <%= f.label :email, "Email" %>
            <%= f.text_field :email %>
          </p>
          <p>
            <%= f.label :telephone, "Telefone" %>
            <%= f.text_field :telephone %>
          </p>
          <p>
            <%= f.label :subject, "Assunto" %>
            <%= f.text_field :subject %>
          </p>
          <p class="textarea">
            <%= f.label :description, "Descrição" %>
            <%= f.text_area :description %>
          </p>
          <p class="button">
            <%= f.submit "Enviar" %>
          </p>
        <% end %>
      </td>
    </tr>
  </table>
</div>

app/views/contacts/new.html.erb
<%= render 'form' %>

app/views/home/index.html.erb
<div class="home">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dooit</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "jquery", "jquery.lightbox-0.5.min", "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div class="geral">
    <div class="topo">
      <div class="menu">
        <ul>
          <% if false %>
          <li>
          <%= link_to "HOME", root_path %>
          </li>
          <% end %>
          <li>
          <%= link_to "QUEM SOMOS", companies_path %>
          </li>
          <% if false %>
          <li>
          <%= link_to "CLIENTES", clients_path %>
          </li>
          <li>
          <%= link_to "SERVIÇOS", services_path %>
          </li>
          <% end %>
          <li>
          <%= link_to "CONTATO", new_contact_path %>
          </li>
        </ul>
      </div>
      <div class="logo">
        <p>
          <%= image_tag("logo.gif") %>
        </p>
        <p class="texto">
        Don't wait, ask to do it.
        </p>
        
        <% if false %>
        <p class="image">
          <%= image_tag("facebook.png") %>
          <%= image_tag("twitter.png") %>
        </p>
        <% end %>
      </div>
    </div>
    
    <%= yield %>
    
    <div class="rodape">
      <p>
        Todos os direitos reservados para Dooit Soluções.
      </p>
    </div>
  </div>
</body>
</html>

app/views/services/index.html.erb
<div class="cases">
  <p class="imagem">
    <%= link_to image_tag("pmpl.png"), "images/pmpl_large.png", :rel => "image"  %>
  </p>
  <p class="texto">
    <ul>
      <li>PMPL (Plano de Manutenção Preventiva de Lubrificação)</li>
      <li></li>
      <li>Controle</li>
      <li>Controle</li>
  </p>
</div>

app/views/services/show.html.erb
<div class="cases">
  <p class="imagem">
    <%= link_to image_tag("pmpl.png"), "images/pmpl_large.png", :rel => "image"  %>
  </p>
  <p class="texto">
    <ul>
      <li>PMPL (Plano de Manutenção Preventiva de Lubrificação)</li>
      <li></li>
      <li>Controle</li>
      <li>Controle</li>
  </p>
</div>